## The server config file

# Use this environment by default, if server is started without the --env switch.
useEnvironment: development
#useEnvironment: production

environments:

  # This is the default configuration set
  default:
    documentRoot: .
    port: 3007
    restapiRoot: ..
    remoteServices: []

  # Override the default config parameters with values specific to the development environment
  development:
    port: 3007
    documentRoot: ../webui

  # development environment with proxying the 'serviceUrlPrefix' requests to the local host
  devProxy:
    port: 3009
    documentRoot: ../webui
    remoteServices:
      -
        uri: /monitoring
        active: true
        host: localhost
        port: 3008
      -
        uri: /*
        active: true
        host: localhost
        port: 3008

  # production environment specific values
  production:
    port: 3008
    documentRoot: ../webui/build/rest-tool-cookbook/examples/crm-api/production
