name: Customers service
description: This is the description of the service to customer collection resources
style: COLLECTION
uriTemplate: /customers
methods:
    GET:
        summary: List all the customers
        notes: List all the customers
        # implementation: api.getCustomers
        request:
            headers:
                -
                    field: Accept
                    content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                -
                    field: Accept-Encoding
                    content: "gzip, deflate"
        responses:
            -
                name: OK
                statusCode: &OkStatusCode 200
                reason: &OkReason Successful execution
                headers:
                    -
                        field: Content-Type
                        content: application/json
                mockBody: getCustomers-responseBody.json
        testCases:
            -
                name: Get Customers
                description: Successfully retrieves all the customers
                url: /customers
                template: testGetMethod.mustache
                request:
                    headers:
                        -
                            field : "Accept"
                            content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                        -
                            field: "Accept-Encoding"
                            content: "gzip, deflate"
                response:
                    name: OK
                    statusCode: *OkStatusCode
                    reason: *OkReason
                    headers:
                        -
                            field: "Content-Type"
                            content: "application/json"
                    validationSchema: getCustomers-responseBody-validationschema.json

    POST:
        summary: Create a new customer
        notes: Create a new customer
        request:
            headers:
                -
                    field: Accept
                    content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                -
                    field: Accept-Encoding
                    content: "gzip, deflate"
        responses:
            -
                name: OK
                statusCode: *OkStatusCode
                reason: *OkReason
                headers:
                    -
                        field: Content-Type
                        content: application/json
                mockBody: postCustomer-responseBody.json
        testCases:
            -
                name: Create Customer
                description: Succesfully creates a new customer
                url: /customers
                template: testPostMethod.mustache
                request:
                    headers:
                        -
                            field : "Accept"
                            content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                        -
                            field: "Accept-Encoding"
                            content: "gzip, deflate"
                    body: postCustomer-responseBody.json
                response:
                    name: OK
                    statusCode: *OkStatusCode
                    reason: *OkReason
                    headers:
                        -
                            field: "Content-Type"
                            content: "application/json"
                    validationSchema: postCustomer-responseBody-validationSchema.json
